FEDERATION_SERVER="https://api.stellar.org/federation"

ACCOUNTS=[""]

[DOCUMENTATION]
ORG_NAME="PT Megantium Sarana Multimedia"
ORG_URL="https://megantium.com"
ORG_LOGO="https://megantium.com/logo.png"

[[CURRENCIES]]
code="MEGA"
issuer=""
status="live"
name="MEGA"
desc="1 MEGA equivalent with 1,000 RUPIAH. How to purchase RUPIAH using XLM and convert it into MEGA ? All detailed informations could be found at https://megantium.com"
conditions="There will be only 10,000,000,000 MEGA existed on SDEX for investors. MEGA will be generate dividends as much as 2.5% per month for 10 years. The dividends send regularly to investor wallets every month." 
display_decimals=2
image="https://megantium.com/logo.png"
fixed_number=10000000000
