# MEGANTIUM
VERSION="2.20.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[""]

[DOCUMENTATION]
ORG_NAME="PT Megantium Sarana Multimedia"
ORG_URL="https://megantium.com"
ORG_LOGO="https://megantium.com/logo.png"

[[CURRENCIES]]
code="MEGA"
issuer=""
image="https://megantium.com/logo.png"
display_decimals=2
status="live"
name="MEGA"
desc="There will be only 10,000,000,000 MEGA existed on SDEX (Stellar Decentralized Exchange). 1 MEGA equivalent with 1,000 RUPIAH. How to purchase RUPIAH using XLM and convert it into MEGA ? All detailed informations could be found at https://megantium.com"
conditions="MEGA will generate dividends as much as 2.5% per month for 10 years."
redemption_instructions="The dividends send regularly to investor wallets every month."
fixed_number=10000000000
